### ISSUE TITLE
delegating pause access 

### ISSUE THREAD

**Issue by tgrecojs** [lari-labs/dapp-ertp-airdrop#109]

**Comment by dckc** [comment]
I gather the policy is clear now; there are a handful of individuals with executive authority.

I think you can skip all the `@agoric/governance` and `committee.js` and such and just use administrator invitations. They would be like oracle operator invitations or economic committee invitations. But the rights they confer would be to pause the contract directly, not to collaboratively vote on a decision nor submit a price for aggregation.

_p.s. We have those examples, but finding the relevant code takes some hunting. We haven't collected them into docs. I can feel a "how do I add administrators to my contract?" github discussion coming on._

cc @jovonni

**Comment by dckc** [comment]
Is this fixed in #119 ? (and hence in 8d9ca6e aka [v0.0.1](https://github.com/hindley-milner-systems/dapp-ertp-airdrop/releases/tag/v0.0.1))

cc @jovonni @otoole-brendan
