### ISSUE TITLE
Setup Contract Baggage

### ISSUE THREAD

**Issue by tgrecojs** [lari-labs/dapp-ertp-airdrop#23]
Chain upgrades occur roughly every 6 weeks. This event forces all contracts live on Agoric's blockchain to go through a resurrection cycle.   1. The contract is alive and well. 2. The contract dies, causing all existing promises to transition into a `rejected` state. 3. The contract is restarted, at which time it must be rebuilt so that it may continue to function as if the restart never occured.

**Comment by dckc** [comment]
> Chain upgrades occur roughly every 6 weeks. This event forces all contracts live on Agoric's blockchain to go through a resurrection cycle. 

Really? Not AFAIK.
What's the source of this info?

**Comment by tgrecojs** [comment]
I think this was a rough estimate from @0xpatrickdev during a conversation we had a few weeks back. we were discussing whether or not upgradability was need, so the comment became irrelevant once I realized that all mn2 deployments must be upgradable.

closing this as the contract makes use of baggage via `@agoric/zone`
