### ISSUE TITLE
Deploy to testnet

### ISSUE THREAD

**Issue by tgrecojs** [lari-labs/dapp-ertp-airdrop#25]
Deployment to public testnet
**Task:** Deploy your completed contract(s) to a public testnet (e.g., DevNet).
**Purpose:** Demonstrate contract can be deployed and operates correctly outside of your local environment

----

earlier:

**Task**: Dapps must make a maximum of 2 RPC calls every 1 second. **Purpose**: Avoid spamming RPC nodes and reducing their availability. **Instructions**: Maximum 2 requests per second to the RPC server ([per issue](https://github.com/Agoric/agoric-sdk/issues/6870))The [@agoric/rpc](https://github.com/Agoric/ui-kit/tree/main/packages/rpc) library offers batchQuery and chainStorageWatcher modules. ([example](https://github.com/Agoric/dapp-inter/pull/140/files))

**Comment by dckc** [comment]
description looks like a copy-past goof from another item.

[MN2 checklist](https://github.com/Agoric/agoric-sdk/discussions/8280) says:

> Task: Deploy your completed contract(s) to a public testnet (e.g., DevNet). Purpose: Demonstrate contract can be deployed and operates correctly outside of your local environment

**Comment by dckc** [comment]
An Oct 9 update indicates that completing this depends on #110 .

**Comment by dckc** [comment]
Do you want to add any details about which testnet this was deployed to?

[devnet governance](https://devnet.explorer.agoric.net/agoric/gov) doesn't show anything relevant.

**Comment by dckc** [comment]
I presume you consider this in progress.

**Comment by dckc** [comment]
for reference:

[proposal-1.json](https://gist.github.com/dckc/f633cb8b40ccef3cc89af391721e052f#file-proposal-1-json):
```json
{
  "id": "1",
  "messages": [
    {
      "content": {
        "@type": "/agoric.swingset.CoreEvalProposal",
        "title": "tribbles airdrop xnet deployment",
...
      },
      "authority": "agoric10d07y265gmmuvt4z0w9aw880jnsr700jgl36x9"
    }
  ],
...
  "status": "PROPOSAL_STATUS_PASSED",
  "voting_end_time": "2024-11-05T15:51:11.150874279Z",
}
```


[script.js](https://gist.github.com/dckc/f633cb8b40ccef3cc89af391721e052f#file-script-js):
```
const manifestBundleRef = {bundleID:"b1-493618f14e60d8d06de5378d3e426af25253bd789428de08098dadf5b1ba81353c658e4e538e45bca976baeb121c57419eb06c1e173d13567d1275ddc948cbee"};
const getManifestCall = harden([
  "getManifestForAirdrop",
  {
    installKeys: {
      tribblesAirdrop: {
        bundleID: "b1-2ff7c3345606c2c8d65c1f69dbae169036f9a28683b55db4105ad8cc5ca6f005c6e702aee15b12eb0f77b5589df5f3d4bb0783b45d2bca81207fcdaa8c0beb65",
...
```

which matches...

https://github.com/hindley-milner-systems/dapp-ertp-airdrop/releases/tag/v0.0.1 8d9ca6e 


also:

[tx.json](https://gist.github.com/dckc/f633cb8b40ccef3cc89af391721e052f#file-tx-json):
```
{
  "height": "13022",
  "txhash": "7E21F2058BE6000718EF87FE4ECE8D7B87ABDF019A54D6E10D570249E2603061",
}
```


## p.s. 28 Nov deployment

```
2024-11-28T01:26:58.991Z SwingSet: vat: v1: ----- :::: START-TRIBBLES-AIRDROP.JS ::::.2  21 deploy script complete.
```

**Comment by tgrecojs** [comment]
thanks @dckc this slipped passed me until now. 

i really appreciate your "catch and release" of the relevant information.

**Comment by dckc** [comment]
Yesterday, @otoole-brendan started a thread on "putting latest version of Tribbles contract code on Xnet"

**Comment by dckc** [comment]
@tgrecojs and I attempted Tribbles3 and Tribbles4 without quite succeeding.

```
2024-12-05 16:58:58.909	
￼2024-12-05T22:58:58.253Z SwingSet: xsnap: v10: TypeError: defaultRestoreRef: in: no reference
 at makeError (/bundled-source/.../node_modules/ses/src/error/assert.js:351)
 at decodeErrorCommon (/bundled-source/.../node_modules/@endo/marshal/src/marshal.js:309)
 at decodeFromSmallcaps (/bundled-source/.../node_modules/@endo/marshal/src/encodeToSmallcaps.js:437)
 at fromCapData (/bundled-source/.../node_modules/@endo/marshal/src/marshal.js:398)
 at notifyOnePromise (/bundled-source/.../packages/swingset-liveslots/src/liveslots.js:1064)
 at notify (/bundled-source/.../packages/swingset-liveslots/src/liveslots.js:1088)
 at dispatchToUserspace (/bundled-source/.../packages/swingset-liveslots/src/liveslots.js:1358)
 at runWithoutMetering (/bundled-source/.../packages/swingset-xsnap-supervisor/lib/supervisor-subprocess-xsnap.js:59)
 at ()
2024-12-05 16:58:58.909	
￼2024-12-05T22:58:58.252Z SwingSet: xsnap: v10: RemoteTypeError(error:liveSlots:v1#70002)#21: defaultRestoreRef: in: no reference
2024-12-05 16:58:58.909	
￼2024-12-05T22:58:58.233Z SwingSet: vat: v1: TypeError: defaultRestoreRef: in: no reference
 at defaultRestoreRef (#8040:107)
 at defaultRestoreRef (#8040:102)
 at getManifestForAirdrop (.../ertp-airdrop-contract/src/airdrop.proposal.js:289)
 at coreProposalBehavior (#8040:171)
 at ()
 at ()
2024-12-05 16:58:58.909	
￼2024-12-05T22:58:58.232Z SwingSet: vat: v1: TypeError#7: defaultRestoreRef: in: no reference
```

## build-it.js

```js
import { makeHelpers } from '@agoric/deploy-script-support';

import {
  getManifestForAirdrop,
  startAirdrop,
} from '../src/airdrop.proposal.js';

/** @type {import('@agoric/deploy-script-support/src/externalTypes.js').CoreEvalBuilder} */
export const defaultProposalBuilder = async ({ publishRef, install }) => {
  return harden({
    sourceSpec: '../src/airdrop.proposal.js',
    getManifestCall: [
      getManifestForAirdrop.name,
      {
        installKeys: {
          tribblesAirdrop: publishRef(install('../src/airdrop.contract.js')),
        },
      },
    ],
  });
};

export default async (homeP, endowments) => {
  // import dynamically so the module can work in CoreEval environment
  const { writeCoreEval } = await makeHelpers(homeP, endowments);
  await writeCoreEval(startAirdrop.name, defaultProposalBuilder);
};
```

**Comment by dckc** [comment]
## proposal 8 - not quite?

more progress; not seeing logs from the contract; not sure where the error is...

https://gist.github.com/dckc/0a1907bc26ada801eb905a9216bca726

**Comment by dckc** [comment]
## v0.1.2 on fresh xnet

@tgrecojs @jovonni does this look right to you?

[proposal.json](https://gist.github.com/dckc/375c393520423f81f274699445672fa4#file-proposal-json) includes [script.js](https://gist.github.com/dckc/375c393520423f81f274699445672fa4#file-script-js) with the v0.1.2 `elideComments` contract bundle

```js
      tribblesAirdrop: {
        bundleID: "b1-193618b86d74dea35f63eef31c576b353ccb36763c872f5f2cde4a6b8687728d8317efbcd7cf107deed511065c5f95d0f0f83d26bb329fb797c81e0ccb88c23c",
      },
```

```json
["2","2024-12-06T20:46:47.090613796Z","PROPOSAL_STATUS_PASSED","Tribbles testnet deployment"]
```

```
2024-12-06T20:47:12.379Z SwingSet: vat: v1: ----- :::: START-TRIBBLES-AIRDROP.JS ::::.2  21 deploy script complete.
```

vstorage shows **Tribbles** included in `published.agoricNames.issuer`

**Comment by dckc** [comment]
This is done to the satisfaction of @LuqiPan and myself
