### ISSUE TITLE
RPC Rate Limiting

### ISSUE THREAD

**Issue by tgrecojs** [lari-labs/dapp-ertp-airdrop#26]
**Task**: Dapps must make a maximum of 2 RPC calls every 1 second. 

**Purpose**: Avoid spamming RPC nodes and reducing their availability. 

**Instructions**: Maximum 2 requests per second to the RPC server ([per issue](https://github.com/Agoric/agoric-sdk/issues/6870))The [@agoric/rpc](https://github.com/Agoric/ui-kit/tree/main/packages/rpc) library offers batchQuery and chainStorageWatcher modules. ([example](https://github.com/Agoric/dapp-inter/pull/140/files))

**Comment by dckc** [comment]
In a Sep 12 update, I see:

> RPC Rate-Limiting (check)
> Airdrop FE is built using Agoric's UI kit so no more than 2 rpc calls per second is default behavior

Did you mean to close this issue, @tgrecojs ?

cc @jovonni @otoole-brendan

**Comment by tgrecojs** [comment]
yes, closing.
