### ISSUE TITLE
Linting Rules

### ISSUE THREAD

**Issue by tgrecojs** [lari-labs/dapp-ertp-airdrop#28]
**Task**: Agoric OpCo has a set of preferred linting rules for partners to run. The partner contract & dapp should be free of linting errors. 

**Purpose**: Linting rules can either prevent or help to catch common errors that might impact correctness or robustness. 

**Instructions**: [#8274](https://github.com/Agoric/agoric-sdk/discussions/8274)

**Comment by dckc** [comment]
Are you sure you want ton consider this done?

when I check out 2e6ed38 and run `yarn lint` it fails:

```
...
/home/connolly/projects/dapp-ertp-airdrop/contract/src/airdrop.proposal.js
   6:1  warning  Invalid JSDoc tag name "import"                                                  jsdoc/check-tag-names
  18:9  error    'Fail' is assigned a value but never used. Allowed unused vars must match /^_/u  no-unused-vars
...
✖ 77 problems (53 errors, 24 warnings)
```
