### ISSUE TITLE
Contract Upgrade Test

### ISSUE THREAD

**Issue by tgrecojs** [lari-labs/dapp-ertp-airdrop#30]
**Task**: For contracts planned to be upgradable, add a null-upgrade test. 

**Purpose**: Verifies the contract is upgradable and has held enough state durably to continue to function post upgrade. If not performed prior to initial contract deployment, there might be unfixable bugs that prevent upgrade. 

**Instructions**: OpCo recommends writing a test of restarting the contract (“null upgrade”).An example of such a test can be found in: [test-fluxAggregator-service-upgrade.js](https://github.com/Agoric/agoric-sdk/blob/master/packages/inter-protocol/test/swingsetTests/fluxAggregator/test-fluxAggregator-service-upgrade.js)

**Comment by otoole-brendan** [comment]
@tgrecojs discussed this internally. Given the contract is not long-lived (shuts down after 5 days) - that MN2 checklist item can be dropped. It does mean however that the contract pause button becomes more important as a means to be able to protect the chain.

**Comment by tgrecojs** [comment]
@otoole-brendan ok, thanks for the input. I'll close out this issue.

regarding the contract pause button, the code for that has actually been implemented ~2 weeks back.

you can check that commit out here - https://github.com/hindley-milner-systems/dapp-ertp-airdrop/pull/99/commits/6f7a9a1dbc86f58b8ef6e56018f06b5df2152f98

**Comment by dckc** [comment]
let's mark this "not planned" rather than done.

**Comment by dckc** [comment]
not planned; see [Sep 9 comment](#issuecomment-2339298072)
