### ISSUE TITLE
Mainnet Checklist

### ISSUE THREAD

**Issue by tgrecojs** [lari-labs/dapp-ertp-airdrop#32]
[https://github.com/Agoric/agoric-sdk/discussions/8280#discussion-5573291](https://github.com/Agoric/agoric-sdk/discussions/8280#discussion-5573291)

- [x] #28
- [x] #24 
- [x] #27 
- [x] #30 
- [x] #31 
- [x] #26 
- [x] #25 
- [x] #65
- [x] #29

**Comment by dckc** [comment]
Iike #93, now that you have a milestone, I suggest closing this.

**Comment by dckc** [comment]
I'd like to establish a 1-1 correspondence between [issues in this repo tagged mn2-partner-requirements](https://github.com/hindley-milner-systems/dapp-ertp-airdrop/labels/mn2-partner-requirements) and Partner items in [the MN2 checklist](https://github.com/Agoric/agoric-sdk/discussions/8280).

1. Linting Rules
   - #28
2. Full Contract Functionality Coverage in CI
   - #24
3. Contract level pause button
   - #27
4. Upgrade test
   - #30
5. Deployment Test
   - #31
6. RPC rate limiting
   - #26
7. Deployment to public testnet
   - #25
8. Perf testing
   - #65
9. E2E Demo
    - #29

I'm inlined to leave **Production Rollout** items out of scope:
1. Community Posts
2. Bundle Install Preparation
