### ISSUE TITLE
contract interface unclear - overly flexible?

### ISSUE THREAD

**Issue by dckc** [lari-labs/dapp-ertp-airdrop#47]
why is the state machine one of the terms? does the contract really work with an arbitrary state machine?

https://github.com/lari-labs/dapp-ertp-airdrop/blob/e74f41b53e5d8b34044cf646cfc41858b5170530/contract/src/airdrop/prepare.js#L66-L67

passing in a purse seems hazardous. The contract can't be sure the caller isn't messing with the purse.

https://github.com/lari-labs/dapp-ertp-airdrop/blob/e74f41b53e5d8b34044cf646cfc41858b5170530/contract/test/airdropZone/test-airdrop.js#L135

Where is the meme token issuer expected to reside? what contract / vat? Shouldn't this contract make it with `makeZCFMint`?

https://github.com/lari-labs/dapp-ertp-airdrop/blob/e74f41b53e5d8b34044cf646cfc41858b5170530/contract/test/airdropZone/test-airdrop.js#L125

is `startTime` relative or absolute? usage is absolute:

https://github.com/lari-labs/dapp-ertp-airdrop/blob/e74f41b53e5d8b34044cf646cfc41858b5170530/contract/src/airdrop/prepare.js#L175-L176

but some docs suggest relative:

https://github.com/lari-labs/dapp-ertp-airdrop/blob/e74f41b53e5d8b34044cf646cfc41858b5170530/contract/src/airdrop/prepare.js#L44

I suggest using a realistic / plausible time in your tests; for example:

```js
  const noop = () => {};
  const modernTime = BigInt(new Date(2024, 6, 1, 9).valueOf() / 1000);
  const chainTimerService = buildManualTimer(noop, modernTime, {
    timeStep: 60n,
  });
```
https://github.com/Agoric/dapp-agoric-basics/blob/5d800a05eae8b77118ee9a8a27e2943fd91dee5c/contract/test/boot-tools.js#L54-L58

**Comment by dckc** [comment]
and why is `distributionSchedule` in the exo state when it's already available from static scope?

https://github.com/lari-labs/dapp-ertp-airdrop/blob/e74f41b53e5d8b34044cf646cfc41858b5170530/contract/src/airdrop/prepare.js#L110

https://github.com/lari-labs/dapp-ertp-airdrop/blob/e74f41b53e5d8b34044cf646cfc41858b5170530/contract/src/airdrop/prepare.js#L69

**Comment by dckc** [comment]
why is `prepareAirdropCampaign()` not done during the `start()` function?

https://github.com/lari-labs/dapp-ertp-airdrop/blob/e74f41b53e5d8b34044cf646cfc41858b5170530/contract/src/airdrop/prepare.js#L171

**Comment by tgrecojs** [comment]
I think this can be closed. can you confirm? @dckc

**Comment by dckc** [comment]
- [x] state machine terms - gone
 - [ ] looks like the purse hazard is still there. I'm OK to track that under #55
 - [ ] meme token issuer home -> #55 likewise
 - [x] startTime is clearly relative. (maybe "startOffset" or "startDelta" would be more clear.)
 - [x] distributionSchedule
 - [x] prepareAirdropCampaign

so yes.
