### ISSUE TITLE
type inference not working in eslint

### ISSUE THREAD

**Issue by tgrecojs** [lari-labs/dapp-ertp-airdrop#50]
type inference on VS Code isn't working as expected. 

It fails to recognize types that are explicitly imported into files.

![ss_04162024_000293](https://github.com/lari-labs/dapp-ertp-airdrop/assets/6646552/7a7a703b-c4cb-4453-8ef9-40e753f5dc62)

I'm not sure if this error is specific to my computer. Are there any resources that discuss how to get type inference working? if not, then it might be worth sticking something in the docs for solving this. 

cc @dckc

**Comment by dckc** [comment]
> Are there any resources that discuss how to get type inference working?

This is supposed to help:

 - https://github.com/Agoric/agoric-sdk/discussions/8274

It's somewhat in progress.

**Comment by dckc** [comment]
> It fails to recognize types that are explicitly imported into files.

You're using `@import`, which is bleeding-edge stuff... ok, I see `"typescript": "^5.5.0-dev.20240327"`

It works fine here:

![Screenshot at 2024-04-16 11-02-16](https://github.com/lari-labs/dapp-ertp-airdrop/assets/150986/c73f6f49-5d83-4cc0-840b-7ea7cfe41eb0)

Did you tell vs-code to use that version?

![screenshot: TypeScript: Select TypeScript Version](https://res.cloudinary.com/mikebifulco-com/image/upload/c_limit,w_1200/f_auto/q_auto/v1/posts/typescript-vscode-error-fix-last-resort/select-typescript-version?_a=BAVAH6DW0)

ack: [Steps I take to fix stubborn TypeScript errors in VS Code](https://mikebifulco.com/posts/typescript-vscode-error-fix-last-resort) Mike Bifulco February 14, 2023

**Comment by tgrecojs** [comment]
resolved by updating my computers tsc to be the same as the one installed in the dapp.

steps:

1. I updated the typescript version i have installed globally
2. updated my VSCode’s settings.json file to include:
```json
{
  "typescript.tsdk": "/Users/tgreco/.nvm/versions/node/v18.19.1/lib/node_modules/typescript"
}
```

Took these steps after reading through [vscode docs on using latest typescript versions](https://code.visualstudio.com/docs/typescript/typescript-compiling#_using-newer-typescript-versions).
