### ISSUE TITLE
add upload bundle and run core eval to ci tests

### ISSUE THREAD

**Issue by tgrecojs** [lari-labs/dapp-ertp-airdrop#58]

**Comment by dckc** [comment]
dup of #31?

 - #31

**Comment by tgrecojs** [comment]
not a dup, but i'm not entirely sure what the end state of this looks like 🤔  

the goal is to have CI working properly to to test all scenarios agoric requires be covered within the CI pipeline. do you think agoric-basics (or similar dapp) is a good reference for what things should look like when complete?

![ss_09042024_000490](https://github.com/user-attachments/assets/d2d6db69-12b3-4b4f-a247-ff564ace9efe)

@dckc

**Comment by dckc** [comment]
> do you think agoric-basics (or similar dapp) is a good reference for what things should look like when complete?

You've got another issue for Full Contract Functionality in CI; I answered there.

 - #24

**Comment by tgrecojs** [comment]
dupe of #24
