### ISSUE TITLE
use namesByAddress to retroactively send coins to all address who claimed in a given epoch

### ISSUE THREAD

**Issue by tgrecojs** [lari-labs/dapp-ertp-airdrop#63]
In the event that the "bonus mint" threshold is met, then. we reward early claimants by retroactively sending them additional tokens.

**Comment by dckc** [comment]
I suggest moving "use namesByAddress" out of the title and into the description; it's an implementation detail

**Comment by tgrecojs** [comment]
closing as this feature is no longer needed.
