### ISSUE TITLE
Fulfill requirements for "bonus mint"

### ISSUE THREAD

**Issue by tgrecojs** [lari-labs/dapp-ertp-airdrop#64]
## Requirements 
* add `bonusMint` threshold to `startTerms` object.
* configure pub/sub to watch for the threshold to be met.
    * doesn't need to be completely reactive (pay attention to each claim).
    * method on a facet that runs on some interval. 
* once threshold is met, move tokens from `bonusMintPurse`to `airdropPurse`.
* Total supply is determined before contract start time.
* #63

**Comment by dckc** [comment]
It's not clear to me how pub/sub is relevant here. Are there separate publisher and subscriber parties / components? It seems straightforward to just run a check on each claim:

 - have I already checked in this epoch? if so: stop
 - has the threshold been met? if not: stop
 - start sending...
