### ISSUE TITLE
stress test claiming process

### ISSUE THREAD

**Issue by tgrecojs** [lari-labs/dapp-ertp-airdrop#65]
- [x] #111
- [ ] #132 

punted:

- #112

**Comment by dckc** [comment]
I suppose this issue matches the the **Perf testing** item in the [MN2 checklist](https://github.com/Agoric/agoric-sdk/discussions/8280).

> Perform performance and stress testing on the smart contract deployed on our testnet. Build test tools and scripts to simulate high loads, monitor resource usage, and identify bottlenecks. Document results, including performance metrics, failure points, and recommendations for improvement. See also https://github.com/Agoric/agoric-sdk/discussions/9941

Based on our discussion, I suggest:

 - 1 offer to the contract and then
 - 1 per min for 10min
 - 2/min for 10min
 - 5/min for 10min
 - 5/min for 30min

And so on

It's useful to start doing this sort of testing even if offers are just a noop, for a few reasons:

 1. to get a baseline
 2. to get a sense of what scale is feasible
 3. to identify performance bottlenecks early
