### ISSUE TITLE
getIssuer hazardous; redundant w.r.t. getTerms

### ISSUE THREAD

**Issue by dckc** [lari-labs/dapp-ertp-airdrop#89]
No client should rely on the contract to tell it about issuers:

https://github.com/hindley-milner-systems/dapp-ertp-airdrop/blob/277e468fc0de6cfe3059440c2a94e727b5ee1e29/contract/src/airdrop/airdropKitCreator.js#L453-L458

The contract could lie.

Instead, the client should use `E(zoe).getTerms(instance)` and get issuers from there.

These methods on the public facet invite clients to do something that they should not do.

**Comment by tgrecojs** [comment]
awesome @dckc thank you! just removed.

if you check out this helper function you can get some insight into how i'm simulating the process of getting references, making offers, etc. 


https://github.com/hindley-milner-systems/dapp-ertp-airdrop/blob/5563a9fa818774350f830ea2bedbeffb8b2bd01b/contract/test/tribbles-airdrop/actors.js#L15-L59

**Comment by dckc** [comment]
> ... just removed.

ok... fixed in 5563a9f

**Comment by tgrecojs** [comment]
@dckc I noticed that [`mintPayments.js`](https://github.com/Agoric/agoric-sdk/blob/25db2b9d9a51db36ca31fe24f6c97c1826a13f88/packages/zoe/src/contracts/mintPayments.js#L48-L53
) file exposes the token issuer this way. The accompanying comments seem to suggest that this practice is acceptable / not hazardous.

```javascript
  const publicFacet = Far('publicFacet', {
    // Make the token issuer public. Note that only the mint can
    // make new digital assets. The issuer is ok to make public.
    getTokenIssuer: () => issuer,
  });

```

Seeing this example is one of the more frequently referenced sample contracts, I felt it was worth bringing attention to it ↔️   addressing it if necessary

**Comment by Chris-Hibbert** [comment]
the Issuer is expected to be widely shared. It represents the identity of a currency, without carrying any power other than the ability to make new empty purses. The mint (and any purse containing assets) is the powerful thing to be jealously guarded.

**Comment by tgrecojs** [comment]
> the Issuer is expected to be widely shared. It represents the identity of a currency, without carrying any power other than the ability to make new empty purses. The mint (and any purse containing assets) is the powerful thing to be jealously guarded.

Ok, thanks @Chris-Hibbert! So, just to confirm, there isn't any problem with exposing an issuer via publicFacet? 

I understand that in my use case, exposing the issuer can be viewed as redundant, and therefore it is not necessary, however, there may very well be situations that in which exposing the issuer (via publicFacet or some other remote object) would be completely valid. 

Thanks again!

**Comment by Chris-Hibbert** [comment]
> just to confirm, there isn't any problem with exposing an issuer via publicFacet?

Correct. Usually, currencies are well-known, and we want anyone to be able to say "I'd like to sell this item for 40 Euros", which requires they be familiar with the Issuer and the Brand.

There may be situations where a currency's identity is secret, but that isn't normally the case.

**Comment by dckc** [comment]
@Chris-Hibbert while there's no problem sharing an issuer widely, isn't there a hazard that the contract will give a different answer in `getIssuer()` from the one zoe would give in `getTerms()`?

**Comment by Chris-Hibbert** [comment]
Sure, it could, but what would be the point? If a contract lies about what Issuer you should use with it, you won't be able to trade with it. 

Yes, it's more reliable to get Issuers via `getTerms()`.
